# Generated by Django 3.0 on 2020-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
