# Generated by Django 3.0 on 2020-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_month_number_in_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
