# Generated by Django 3.0 on 2020-02-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200201_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('Звичайна', 'Звичайна'), ('Самостійна', 'Самостійна'), ('Зошит', 'Зошит'), ('Контрольна', 'Контрольна'), ('Тематична', 'Тематична'), ('Семестрова', 'Семестрова'), ('Річна', 'Річна'), ('Залік', 'Залік'), ('Екзамен', 'Екзамен')], default='Звичайна', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='rating1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets1', to='diary.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='rating2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets2', to='diary.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='rating3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets3', to='diary.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='rating4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets4', to='diary.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='subject',
            field=models.CharField(choices=[('Укр. мова', 'Укр. мова'), ('Математика', 'Математика')], default='Укр. мова', max_length=100),
        ),
    ]
