# Generated by Django 3.0 on 2020-02-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20200201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingset',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='diary.Subject'),
        ),
    ]
