# Generated by Django 3.0 on 2020-02-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200201_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingset',
            name='subject',
        ),
    ]
