# Generated by Django 3.0 on 2020-02-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_remove_ratingset_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingset',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='diary.Subject'),
            preserve_default=False,
        ),
    ]
