# Generated by Django 3.0 on 2020-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_ratingset_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
